alias: null
batch_size: 32
context_size: 1
decoder_hidden_size: 64
decoder_layers: 1
drop_last_loader: false
early_stop_patience_steps: -1
encoder_bias: true
encoder_dropout: 0.0
encoder_hidden_size: 64
encoder_n_layers: 1
futr_exog_list:
- year
- month
- day_of_week
- weekend
- hour
- holidays
h: 250
hist_exog_list:
- ConsumptionGWh
- ProductionGWh
- waterSE1(MWh)
- windSE1(MWh)
- trmSE1MWh
- waterSE2(MWh)
- windSE2(MWh)
- solSE2MWh
- trmSE2MWh
- OthSE2MWh
- waterSE3(MWh)
- windSE3(MWh)
- nucSE3(MWh)
- solSE3MWh
- trmSE3MWh
- OthSE3MWh
- waterSE4(MWh)
- windSE4(MWh)
- solSE4MWh
- trmSE4MWh
- OthSE4MWh
- TDK1SE3
- TNO1SE3
- TSE2SE3
- TF1SE3
- TSE4SE3
- TSE3DK1
- TSE3NO1
- TSE3SE2
- TSE3F1
- TSE3SE4
- F_LOWSE2SE3
- F_LOWSE3FI
- F_LOWSE3SE4
- C_SE4SE3
- C_DK1SE3
- C_FISE3
- C_NO1SE3
- C_SE2SE3
- C_SE3DK1
- C_SE3FI
- C_SE3NO1
- C_SE3SE2
- C_SE3SE4
- ESE3_FI
- ESE3_NO1
- ESE3_DK1
- ESE3_SE4
- ESE3_SE2
- EFI_SE3
- EDK1_SE3
- ESE2_SE3
- ESE4_SE3
- ENO1_SE3
- Temperature(day)
- PrecipitationEnergySE(day)
- Wind(Pite)
- HydroRes(GWh_week)
inference_input_size: -1
input_size: 500
learning_rate: 0.001
loss: !!python/object:neuralforecast.losses.pytorch.MAE
  _backward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _backward_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _buffers: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks_always_called: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks_with_kwargs: !!python/object/apply:collections.OrderedDict
  - []
  _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _forward_pre_hooks_with_kwargs: !!python/object/apply:collections.OrderedDict
  - []
  _is_full_backward_hook: null
  _load_state_dict_post_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _modules: !!python/object/apply:collections.OrderedDict
  - []
  _non_persistent_buffers_set: !!set {}
  _parameters: !!python/object/apply:collections.OrderedDict
  - []
  _state_dict_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  horizon_weight: null
  is_distribution_output: false
  output_names:
  - ''
  outputsize_multiplier: 1
  training: true
max_steps: 100
num_lr_decays: -1
num_workers_loader: 0
random_seed: 1
scaler_type: minmax
stat_exog_list: null
val_check_steps: 100
valid_batch_size: null
valid_loss: null
